#!/usr/bin/env python3
import datetime
import os
import sys
from collections import defaultdict

try:
    import dns.zone
    from dns.rdatatype import A
except ImportError:
    print("Error: 'dnspython' is required. Run: pip install dnspython")
    sys.exit(1)

# --- REPO CONFIGURATION ---
CONFIG_DIR = "./config"
# Name of the secondary config file to be included in named.conf
REVERSE_CONF_NAME = "named.conf.reverse"

ZONE_FILES = [f for f in os.listdir(CONFIG_DIR) if f.endswith(".zone")]
PRIMARY_NS = "ns.dns.puvvadi.net."
ADMIN_EMAIL = "info.puvvadi.net."
TODAY_SERIAL = datetime.datetime.now().strftime("%Y%m%d01")


def parse_all_zones():
    reverse_map = defaultdict(list)

    for zone_file in ZONE_FILES:
        file_path = os.path.join(CONFIG_DIR, zone_file)
        try:
            with open(file_path, "r") as f:
                origin = None
                for line in f:
                    if line.strip().startswith("$ORIGIN"):
                        origin = line.split()[1]
                        if not origin.endswith("."):
                            origin += "."
                        break

            if not origin:
                continue

            zone = dns.zone.from_file(file_path, origin=origin)
            print(f"Parsing: {zone_file} -> Origin: {origin}")

            for name, node in zone.nodes.items():
                if str(name).startswith("*"):
                    continue

                for rdataset in node.rdatasets:
                    if rdataset.rdtype == A:
                        for rdata in rdataset:
                            ip = rdata.address
                            fqdn = origin if str(name) == "@" else f"{name}.{origin}"

                            parts = ip.split(".")
                            if len(parts) == 4:
                                subnet = ".".join(parts[:3])
                                last_octet = parts[3]
                                reverse_map[subnet].append((int(last_octet), fqdn))

        except Exception as e:
            print(f"Failed to parse {zone_file}: {e}")

    return reverse_map


def write_reverse_zones_and_config(reverse_map):
    named_conf_entries = []

    # 1. Generate the individual reverse zone database files
    for subnet, records in reverse_map.items():
        records.sort(key=lambda x: x[0])
        subnet_parts = subnet.split(".")
        reverse_zone_name = (
            f"{subnet_parts[2]}.{subnet_parts[1]}.{subnet_parts[0]}.in-addr.arpa"
        )
        file_name = f"db.{subnet}.reverse"
        output_path = os.path.join(CONFIG_DIR, file_name)

        print(f"Generating Reverse Zone File: {output_path}")

        with open(output_path, "w") as f:
            f.write(f"$ORIGIN {reverse_zone_name}.\n")
            f.write(f"$TTL 86400\t; 1 day\n")
            f.write(f"@               IN      SOA     {PRIMARY_NS} {ADMIN_EMAIL} (\n")
            f.write(f"                                {TODAY_SERIAL} ; serial\n")
            f.write(f"                                3600       ; refresh (1 hour)\n")
            f.write(f"                                3600       ; retry (1 hour)\n")
            f.write(f"                                2419200    ; expire (4 weeks)\n")
            f.write(f"                                3600       ; minimum (1 hour)\n")
            f.write(f"                                )\n\n")
            f.write(f"                IN      NS      {PRIMARY_NS}\n\n")
            f.write(f"; Autogenerated PTR records\n")

            for last_octet, fqdn in records:
                f.write(f"{last_octet:<15} IN      PTR     {fqdn}\n")

        # Map to the path BIND sees inside the container (/etc/bind/...)
        conf_snippet = (
            f'zone "{reverse_zone_name}" IN {{\n'
            f"  type master;\n"
            f'  file "/etc/bind/{file_name}";\n'
            f"}};\n"
        )
        named_conf_entries.append(conf_snippet)

    # 2. Generate the automated named.conf.reverse file
    reverse_conf_path = os.path.join(CONFIG_DIR, REVERSE_CONF_NAME)
    print(f"Updating configuration index: {reverse_conf_path}")

    with open(reverse_conf_path, "w") as f:
        f.write(
            f"// Autogenerated by generate_ptr.py on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        )
        f.write("// DO NOT EDIT THIS FILE MANUALLY\n\n")
        for entry in named_conf_entries:
            f.write(entry + "\n")

    print("\nSynchronization complete!")


if __name__ == "__main__":
    records = parse_all_zones()
    if records:
        write_reverse_zones_and_config(records)
    else:
        print("No A records found to process.")
