#!/usr/bin/env python3
import datetime
import os
import sys
from collections import defaultdict

try:
    import dns.zone
    from dns.rdatatype import A
except ImportError:
    print("Error: 'dnspython' is required. Run: pip install dnspython")
    sys.exit(1)

# --- REPO CONFIGURATION ---
CONFIG_DIR = "./config"
REVERSE_CONF_NAME = "named.conf.reverse"

PRIMARY_NS = "ns.dns.puvvadi.net."
ADMIN_EMAIL = "info.puvvadi.net."
TODAY_SERIAL = datetime.datetime.now().strftime("%Y%m%d01")


def parse_all_zones():
    reverse_map = defaultdict(list)

    # Ensure the target directory actually exists
    if not os.path.exists(CONFIG_DIR):
        print(f"ERROR: Base configuration folder '{CONFIG_DIR}' could not be located.")
        sys.exit(1)

    # Gather all zone files inside the target folder
    zone_files = [f for f in os.listdir(CONFIG_DIR) if f.endswith(".zone")]

    for zone_file in zone_files:
        file_path = os.path.join(CONFIG_DIR, zone_file)
        try:
            with open(file_path, "r") as f:
                origin = None
                for line in f:
                    if line.strip().startswith("$ORIGIN"):
                        origin = line.split()[1]
                        if not origin.endswith("."):
                            origin += "."
                        break

            if not origin:
                continue

            zone = dns.zone.from_file(file_path, origin=origin)
            print(f"Successfully Parsed: {zone_file} -> Domain Origin: {origin}")

            for name, node in zone.nodes.items():
                # Filter wildcards cleanly out of reverse mapping logic
                if str(name).startswith("*"):
                    continue

                for rdataset in node.rdatasets:
                    if rdataset.rdtype == A:
                        for rdata in rdataset:
                            ip = rdata.address
                            fqdn = origin if str(name) == "@" else f"{name}.{origin}"

                            parts = ip.split(".")
                            if len(parts) == 4:
                                subnet = ".".join(parts[:3])
                                last_octet = parts[3]
                                reverse_map[subnet].append((int(last_octet), fqdn))

        except Exception as e:
            print(f"Skipping processing on file {zone_file} due to parser error: {e}")

    return reverse_map


def write_reverse_zones_and_config(reverse_map):
    named_conf_entries = []

    # Iterate through mapped subnets to write the actual zone zonefiles first
    for subnet, records in reverse_map.items():
        records.sort(key=lambda x: x[0])
        subnet_parts = subnet.split(".")

        # Proper reverse notation format calculation (Octet 3 . Octet 2 . Octet 1)
        reverse_zone_name = (
            f"{subnet_parts[2]}.{subnet_parts[1]}.{subnet_parts[0]}.in-addr.arpa"
        )
        file_name = f"db.{subnet}.reverse"
        output_path = os.path.join(CONFIG_DIR, file_name)

        print(f"Writing Database Map -> {output_path}")

        with open(output_path, "w") as f:
            f.write(f"$ORIGIN {reverse_zone_name}.\n")
            f.write(f"$TTL 86400\t; 1 Day Default\n")
            f.write(f"@               IN      SOA     {PRIMARY_NS} {ADMIN_EMAIL} (\n")
            f.write(f"                                {TODAY_SERIAL} ; Serial\n")
            f.write(f"                                3600       ; Refresh\n")
            f.write(f"                                3600       ; Retry\n")
            f.write(f"                                2419200    ; Expire\n")
            f.write(f"                                3600       ; Minimum TTL\n")
            f.write(f"                                )\n\n")
            f.write(f"                IN      NS      {PRIMARY_NS}\n\n")

            for last_octet, fqdn in records:
                f.write(f"{last_octet:<15} IN      PTR     {fqdn}\n")

        # Define internal paths mapping exactly to the container context
        conf_snippet = (
            f'zone "{reverse_zone_name}" IN {{\n'
            f"  type master;\n"
            f'  file "/etc/bind/{file_name}";\n'
            f"}};"
        )
        named_conf_entries.append(conf_snippet)

    # Write out the secondary structural configuration profile link index
    reverse_conf_path = os.path.join(CONFIG_DIR, REVERSE_CONF_NAME)
    print(f"Compiling Zone File Link Configuration -> {reverse_conf_path}")

    with open(reverse_conf_path, "w") as f:
        f.write(
            f"// Autogenerated by generate_ptr.py on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        )
        f.write("// DO NOT MODIFIED THIS CONFIGURATION FILE MANUALLY\n\n")
        for entry in named_conf_entries:
            f.write(entry + "\n\n")

    print("\nData tables completely synchronized.")


if __name__ == "__main__":
    records = parse_all_zones()
    if records:
        write_reverse_zones_and_config(records)
    else:
        print("No dynamic record maps caught. Operation halted.")
